---
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Network

# ------------------------------------------------------------#
#  Parameters
# ------------------------------------------------------------#
Parameters:
  SystemName:
    Type: String
    Description: sample

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-vpc

# ------------------------------------------------------------#
#  InternetGateway
# ------------------------------------------------------------#
  internetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-igw
  attachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref vpc
      InternetGatewayId: !Ref internetGateway

# ------------------------------------------------------------#
#  Subnet
# ------------------------------------------------------------#
  publicSubnetAlb1a:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-subnet-alb-1a
      VpcId: !Ref vpc
  publicSubnetAlb1c:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-subnet-alb-1c
      VpcId: !Ref vpc
  publicSubnetAdmin1a:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.240.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-subnet-admin-1a
      VpcId: !Ref vpc
  publicSubnetAdmin1c:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.241.0/24
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-subnet-admin-1c
      VpcId: !Ref vpc
  privateSubnetApp1a:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.8.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-app-1a
      VpcId: !Ref vpc
  privateSubnetApp1c:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.9.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-app-1c
      VpcId: !Ref vpc
  privateSubnetDb1a:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.16.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-db-1a
      VpcId: !Ref vpc
  privateSubnetDb1c:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.17.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-db-1c
      VpcId: !Ref vpc
  privateSubnetIf1a:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1a
      CidrBlock: 10.0.248.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-if-1a
      VpcId: !Ref vpc
  privateSubnetIf1c:
    Type: AWS::EC2::Subnet
    DependsOn: attachGateway
    Properties:
      AvailabilityZone: ap-northeast-1c
      CidrBlock: 10.0.249.0/24
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-subnet-if-1c
      VpcId: !Ref vpc

# ------------------------------------------------------------#
#  ElasticIP, NatGateway
# ------------------------------------------------------------#
  # eIP1a:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  # nat1a:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     AllocationId:
  #       Fn::GetAtt:
  #         - eIP1a
  #         - AllocationId
  #     SubnetId: !Ref publicSubnetAlb1a
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SystemName}-ngw-1a
  # eip1c:
  #   Type: AWS::EC2::EIP
  #   Properties:
  #     Domain: vpc
  # nat1c:
  #   Type: AWS::EC2::NatGateway
  #   Properties:
  #     AllocationId:
  #       Fn::GetAtt:
  #         - eip1c
  #         - AllocationId
  #     SubnetId: !Ref publicSubnetAlb1c
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${SystemName}-ngw-1c

# ------------------------------------------------------------#
#  RouteTable
# ------------------------------------------------------------#
  publicRouteTableAlb:
    Type: AWS::EC2::RouteTable
    DependsOn: attachGateway
    Properties:
      VpcId: !Ref vpc
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-alb-rt
  publicRouteAlb:
    Type: AWS::EC2::Route
    DependsOn: attachGateway
    Properties:
      RouteTableId: !Ref publicRouteTableAlb
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGateway
  publicRouteTableAdmin:
    Type: AWS::EC2::RouteTable
    DependsOn: attachGateway
    Properties:
      VpcId: !Ref vpc
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-public-admin-rt
  publicRouteAdmin:
    Type: AWS::EC2::Route
    DependsOn: attachGateway
    Properties:
      RouteTableId: !Ref publicRouteTableAdmin
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref internetGateway
  privateRouteTableApp:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref vpc
      Tags:
      - Key: Name
        Value: !Sub ${SystemName}-private-app-rt
  # privateRouteApp:
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref privateRouteTableApp
  #     DestinationCidrBlock: 0.0.0.0/0
  # privateRouteTable1c:
  #   Type: AWS::EC2::RouteTable
  #   DependsOn: nat1c
  #   Properties:
  #     VpcId: !Ref vpc
  #     Tags:
  #     - Key: Name
  #       Value: !Sub ${SystemName}-Private-RT1c
  # privateRoute1c:
  #   Type: AWS::EC2::Route
  #   DependsOn: nat1c
  #   Properties:
  #     RouteTableId: !Ref privateRouteTable1c
  #     DestinationCidrBlock: 0.0.0.0/0
  #     NatGatewayId: !Ref nat1c
  # privateRouteTable2:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !Ref vpc
  #     Tags:
  #     - Key: Name
  #       Value: !Sub ${SystemName}-Private-RT2

  publicSubnetAlb1aRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnetAlb1a
      RouteTableId: !Ref publicRouteTableAlb
  publicSubnetAlb1cRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnetAlb1c
      RouteTableId: !Ref publicRouteTableAlb
  publicSubnetAdmin1aRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnetAdmin1a
      RouteTableId: !Ref publicRouteTableAdmin
  publicSubnetAdmin1cRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref publicSubnetAdmin1c
      RouteTableId: !Ref publicRouteTableAdmin
  privateSubnetApp1aRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref privateSubnetApp1a
      RouteTableId: !Ref privateRouteTableApp
  privateSubnetApp1cRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref privateSubnetApp1c
      RouteTableId: !Ref privateRouteTableApp
  # privateSubnet2aRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId: !Ref privateSubnetDb1a
  #     RouteTableId: !Ref privateRouteTable2
  # privateSubnet2cRouteTableAssociation:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     SubnetId: !Ref privateSubnetDb1c
  #     RouteTableId: !Ref privateRouteTable2

# ------------------------------------------------------------#
#  Outputs
# ------------------------------------------------------------#
Outputs:
  vpc:
    Value: !Ref vpc
    Export:
      Name: !Sub ${SystemName}-vpc
  publicSubnetAlb1a:
    Value: !Ref publicSubnetAlb1a
    Export:
      Name: !Sub ${SystemName}-public-subnet-alb-1a
  publicSubnetAlb1c:
    Value: !Ref publicSubnetAlb1c
    Export:
      Name: !Sub ${SystemName}-public-subnet-alb-1c
  publicSubnetAdmin1a:
    Value: !Ref publicSubnetAdmin1a
    Export:
      Name: !Sub ${SystemName}-public-subnet-admin-1a
  publicSubnetAdmin1c:
    Value: !Ref publicSubnetAdmin1c
    Export:
      Name: !Sub ${SystemName}-public-subnet-admin-1c
  privateSubnetApp1a:
    Value: !Ref privateSubnetApp1a
    Export:
      Name: !Sub ${SystemName}-private-subnet-app-1a
  privateSubnetApp1c:
    Value: !Ref privateSubnetApp1c
    Export:
      Name: !Sub ${SystemName}-private-subnet-app-1c
  privateSubnetDb1a:
    Value: !Ref privateSubnetDb1a
    Export:
      Name: !Sub ${SystemName}-private-subnet-db-1a
  privateSubnetDb1c:
    Value: !Ref privateSubnetDb1c
    Export:
      Name: !Sub ${SystemName}-private-subnet-db-1c
  privateSubnetIf1a:
    Value: !Ref privateSubnetIf1a
    Export:
      Name: !Sub ${SystemName}-private-subnet-if-1a
  privateSubnetIf1c:
    Value: !Ref privateSubnetIf1c
    Export:
      Name: !Sub ${SystemName}-private-subnet-if-1c
  publicRouteTableAdmin:
    Value: !Ref publicRouteTableAdmin
    Export:
      Name: !Sub ${SystemName}-public-admin-rt
  privateRouteTableApp:
    Value: !Ref privateRouteTableApp
    Export:
      Name: !Sub ${SystemName}-private-app-rt
