---
AWSTemplateFormatVersion: '2010-09-09'
Description: WAF

# ------------------------------------------------------------#
#  Parameters
# ------------------------------------------------------------#
Parameters:
  SystemName:
    Type: String
    Description: sample

Resources:
# ------------------------------------------------------------#
#  WAF
# ------------------------------------------------------------#
  wafWebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn:
        Fn::ImportValue:
          !Sub "${SystemName}-app-alb"
      WebACLArn: !GetAtt wafWebAcl.Arn

  wafWebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${SystemName}-waf-webacl
      DefaultAction: 
        Block: {}
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${SystemName}-waf-webacl
      Scope: REGIONAL
      Rules: 
        - 
          Name: !Sub ${SystemName}-waf-webacl-rule
          Priority: 0
          OverrideAction: 
            None: {}
          Statement: 
            RuleGroupReferenceStatement: 
              Arn: !GetAtt wafRuleGroup.Arn
          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${SystemName}-waf-webacl-rule

  wafRuleGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties:
      Name: !Sub ${SystemName}-waf-role-group
      Capacity: 1500
      VisibilityConfig: 
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${SystemName}-waf-rule-group
      Scope: REGIONAL
      Rules: 
        - 
          Name: !Sub ${SystemName}-waf-rule-sqli
          Priority: 0
          Action: 
            Block: {}
          Statement: 
            OrStatement: 
              Statements: 
              - 
                SqliMatchStatement: 
                  FieldToMatch: 
                    UriPath: {}
                  TextTransformations: 
                    - 
                      Priority: 0
                      Type: NONE
              - 
                SqliMatchStatement: 
                  FieldToMatch: 
                    QueryString: {}
                  TextTransformations: 
                    - 
                      Priority: 0
                      Type: "NONE"
              - 
                SqliMatchStatement: 
                  FieldToMatch: 
                    Body: {}
                  TextTransformations: 
                    - 
                      Priority: 0
                      Type: "NONE"
          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${SystemName}-waf-rule-sqli
        - 
          Name: !Sub ${SystemName}-waf-rule-xss
          Priority: 1
          Action: 
              Block: {}
          Statement: 
            OrStatement: 
              Statements: 
                - 
                  XssMatchStatement: 
                    FieldToMatch: 
                      UriPath: {}
                    TextTransformations: 
                      - 
                        Priority: 0
                        Type: "NONE"
                - 
                  XssMatchStatement: 
                    FieldToMatch: 
                      QueryString: {}
                    TextTransformations: 
                      - 
                        Priority: 0
                        Type: "NONE"
                - 
                  XssMatchStatement: 
                    FieldToMatch: 
                      Body: {}
                    TextTransformations: 
                      - 
                        Priority: 0
                        Type: "NONE"
          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${SystemName}-waf-rule-xss
        - 
          Name: "sample-waf-rule-headeer"
          Priority: 2
          Action: 
            Allow: {}
          Statement: 
            ByteMatchStatement: 
              SearchString: 8f856a61-e356-45c9-91b3-0fb8f0ebc47a
              FieldToMatch: 
                SingleHeader: 
                  Name: "x-sample-id"
              TextTransformations: 
                - 
                  Priority: 0
                  Type: "NONE"
              PositionalConstraint: "EXACTLY"
          VisibilityConfig: 
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: !Sub ${SystemName}-waf-rule-header